data <- read.table(pipe('findstr /B /R ^[1-2]/2/2007 household_power_consumption.txt'),header=F, sep=';')
png("plot2.png",width=480,height=480)
datetime <- strptime( paste(data$V1,data$V2), format="%d/%m/%Y %H:%M:%S")
with(data, plot(datetime, V3, type="l",xlab="",ylab="Global Active Power(kilowatts)"))
dev.off()
